#! /bin/sh
# /etc/init.d/temperatura-interna

### BEGIN INIT INFO
# Provides:          temperatura-interna
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here
/home/pi/Documents/raspberry-misc/temperatura-interna-raspberry.py

# Carry out specific functions when asked to by the system
case "$1" in
 start)
	 echo "Starting noip"
	 # run application you want to start
	 /home/pi/Documents/raspberry-misc/temperatura-interna-raspberry.py
	 ;;
 stop)
	 echo "Stopping noip"
	 # kill application you want to stop
	 killall temperatura-interna
	 ;;
 *)
	 echo "Usage: /etc/init.d/noip {start|stop}"
	 exit 1
	 ;;
esac

exit 0
